name: Server publish automation

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node Packages
      run: yarn install
    - name: Generate server build
      run: yarn run build

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibmlmdHktbWVtb3J5LTI4NDgxNiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjcyYWZhNDEyN2I3NzExZGEyNWVlMjc3OTNiZDZiYjBkYmRjYzVlZDMiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREFaM3habHgyTDh3SmVcbm1CRUlyV2NaTDQ5SGVweWo4N2MxRjlwOSs2MnRTdnNSMUQ5Y25VWUZhTmtLSy9BcHFUVmxMbWd3QkZxdHkzcW1cbm1xSExRS3YrMmVzbm1kQ04yOGtKUnM4RUduWGtla0tnWjEyekRzN2pkaXNuVXVUQ283eml3aEdXbjZuU0lZRHdcbmd2MWtTVmd4UkxUbllVUTZxR1ZUSXE4V1ZmK3dueGR0bkRjQ1pXRVA5by9ESVhTbUdpN3E0OUpOUEc3SkJTY0ZcbkY0dk9hQWFIN0ROUTByQmVHcE5JZThJKy9vN3VTTHNDMk16cEhQYy9SaEhlT1h2L01pZzJZbXRjamFubnVtVFJcbkQ5MjhTalRXMFZEcUJ2ZkZHNGphZnVkZHlBWkl6b3pnTyt2OXc1emhPYXZQYTZTZldjdkwxUmhoNmZQMTF0eGVcbllrSSt6b2pkQWdNQkFBRUNnZ0VBSWQxVkRyUEJXSk9TRkRJeHRWUkg5Qy9oeVJQMHBBck9jVUxjaXhZVU1JOGtcbjk3TmkzNXN5NnRyVWNLemhIWVFSeU5oTk1ENWo4M2tBQW5qdkIwWS92NkI5ZWovaGJFYUY4T01NcHMwOWVOUm9cbkM3R0YxWEZDeXRoT3FpSTE3MmhBWTYwQ3lYOGF0Y2g5MkZkRjREUGttTzlkNCtmRHlZdEFJa3pWZ2xucW9oeGZcbnlLOTFvcStheGlVR2crTjVZRXBuZzVuZEdEZmFsa1lCaTdaQTYyRE9CTTgzMitVcUpUckZOR3JFeG9tTGpvTVpcbm5kVE5YZk5abEplK1Fxb0NvcE5Id3N2QlpKeWpFNlI3UHVsUkduRjNraFdHQTZENG9rVlUzRlN4Y1M5QzJWZVVcbnF2Z2hEZ0pqaWxDdnR4SU9sbjQxVlFhcHZsR3ArR1BFS3l2N1NldHVRUUtCZ1FEMkp4OHR0b09lVG53ekVBbGRcbjN3dWJLSm45Q1FURnptTE1OWHBwRG1lN2FOT3dQYnphdzFpelFqdnJmVWhrR1AvaWRxb0tUZ0Y5S1pkdTYralpcbmY5Uk5ZdmtzaEl0RnoxRGhFdFYwZDJYYlhCRzdydGladVhIZU5WVVJYbDJRRS8vZVhhTVMwY0NZZm50ZmIydFdcbjdtMlpqVHl0WVloVENuVGZud1pZR05LTTBRS0JnUURJR2VzNEU2Ti9qMWtEV2VZOHBRUnF2dHk4eVJGYjFRdzRcbmpQNXdnRnRZQmp2bFFWdWIrMTNpY0hlYlArVk55VTdLZE5OejB6ZmxEc3VKRlJCUDFpcWx0eXQwZjhTY2wrYUNcbmlUSWgvVTVNMXRrOGVnaHU0b29QZEdvaWtVRTV6Z3J2czdGMXp6Q0FVZDhUdytYOVlpbStBMHVBUTFvTjR6TURcbmlqOUF1Z3JPVFFLQmdDNjdPcVlaRWwvSmtyYTNBckE1bWlCNDB0TkJGUkRnbjgwWkVnWkQzOW1xaXhYWWdyUWRcbmhnZHlPYUg1aFBiTDhEaDBRcy8yQXo1WjJSQUw1WWIxUjc3eFhWRGdVUGlONVZMMW1tU2tEa2hZOEZ6clV0L01cblh4dktrRDNkNW5GbCtwdWl0MFRwWVdFU0VpWUtKeHkzNDBMVmw0RnJGTkIvR2JVaW9iZXo3clVoQW9HQWZBTFVcbkxDUy9wMGFIdS9QekpKS0Fja2RuTmZqR3NVc1FEOXdSdEZkWVJPMVlJWFNuK2J1SEs5Ylh5WGVIL1BWTngxc3ZcbjBSQ09DMzluMU1VaEh0bDBCTS9JTnFNWWpwUDFYK0QzR09tTHBVTmh6b0V5eU1YTkdsYmprQmpGZTdXZVFYL3pcbjh6YzhyOG9Obm9wQjl3N25IOE9hL3hxK3JPeXBxUC84dzNpSlNlRUNnWUVBeUNDdVZLN2txTjJnZDd2SjJKMWNcblViVjBqUEd1bVYwbkdkNmJtRzhMSkNmbjg4dzNGUmF6akJFQkNNeFI3YU5SWFpkbS83QUNRUXJmbThuemRabHBcbk9YR1E1U1FZWWVKT055Vnd2VUhZaHplSzBJU0VXYUFGZFJZcVBTbnl0L0FaNHlRSERLMmo4TFZpUVdSNkt3ZytcbnhPbVhJSGl1aE53L2xhUXNTNEV0RmVVPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogIm5pZnR5LW1lbW9yeS0yODQ4MTZAYXBwc3BvdC5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwMDIyMTQxMjAwMjQzMzA5NjE1NSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvbmlmdHktbWVtb3J5LTI4NDgxNiU0MGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
        project_id: nifty-memory-284816

    - name: Publish app to Google App Engine
      run: |
        # This client-secret.json is converted by GCP_SA_KEY.
        # gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
        # gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml
        
        # Suppose you need a cron task.
        # gcloud -q app deploy cron.yaml