name: Server publish automation

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node Packages
      run: yarn install
    - name: Generate server build
      run: yarn run build

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: github@nifty-memory-284816.iam.gserviceaccount.com
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibmlmdHktbWVtb3J5LTI4NDgxNiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjMyYWJkNzMxYmFmMjlkNTJjMzY5ZTdhNGIyMmMwNzQ0YTU0Mjk0MmMiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzBKV2lKTEFxMkhLRXhcbkRpWmd2VUpmaWJsdHd2MFo3Q081WkRUcDFiNkpYN3hsNC9MK3RyVjRhRncxdVUxSHM5TGl6OWtRZ3Izc2xpbEtcbmQ1bHFQd2JuTUJXN0dONmFaUW9zRE11clNEYVVqbWUrV1hacHRxRFZFam5xVnlMNjlLdkJ5SFpkQStaWWV0c2hcblg0WVdJb0I3Sy9nYVhiWnpic0prN0Q5TzBkK0lKc2d1bitFcUMvU1h0ekpkZm8vcXBZVXpjSW5HZ1FkNXZhTXlcbkxZdjJBdkhtci9QN2NoMW5SUXVHSU8rdkdscXpxcGFPaHNaM2Q5ZFFwcW5rUFh4V2hXZDlOSFJIaExYbitzM2dcbjhZMVBpeGlJOVZNWTQ4UmFMdE1jaWJadXE3OGZJT3pEQTNtV0NiTVU2RjFwYVRBTDM4ellNcEdBdWZDUGpVemdcbnNTSTJ6RWRyQWdNQkFBRUNnZ0VBQk5pWXhrL2ovZUFwU2V1S2hzR3dubWRURUt2VktUUmNCYW0zYnE3c1VEKytcbkRyT2lIczRGZGJiQS9FVCsyalh4TDE3T0JRNnZVMFQ2MldEOFJJcHJnaDZlQndsMU80d0tTUU1URzRsMnhtcEtcblNpbVg4T0lUMDRlSS9VL1l4ZzE4N1ZxYUxJaGxVdTRESlJPdnhMcXE0Q1ZmcUQzcklaSFNNdXJVRFNmQ0xxUm9cbjRsajBRSmNkc3ZQNUlzZmptMWJPbWZFWmh3ajFMK1h3QSthQ3U1TGNQdC9odnAydCtyVXFNb3ZJUkhNUFVZcFBcbjR2OERSb2dtNjl3MTR6eG5GWFBHSDkxTDczTU1zckRIbDlYY1ZIQ2M4V3JGSlBYdCtGckNQMmhSQmhMZk02YW9cbld0Qzk5SWlYQWx3dTFIYW81MFRnSVlmOWpQUDdlM0M1bzY0cXJyOGNxUUtCZ1FEV3k2bEk5dlIvSXMwandxZUpcblRtRnlKVDRrWmNpTjZpWVlvSVFMekp4NjVtRkFjdkx0TlBkU2dqaGR0dWpGdFl1MjVIcG1VcnVBU08reDVia3BcbkVGSkNENnk0ajc1OU1aRzlnenZhZ1FKbUQwZFBYd3hDK01oekc4aHJ6WVllM25Hd3kvM3h0dWozYTAzOCsxNWhcbndXVEJZK0tUVE9UTnIxWU5zeTRMQWZzUFJRS0JnUURXdENoUVBqZ1dvR0QzL1A4TDh5OVJoK3g3dUZydDVJVWNcbjBPVmhFejRmb0FSRDhTRW5JeTVmTEpIRGM1SjRBbUtmbFV4ZlZwLzFjd0RxYk5VRGs1MmsrTjRwR0h2LzFFRHlcbkV0eThNNXM2WW56L2pkVldXNkdJTTM3ZWllM1RsSDFJUFNSK1AzZFh4SEE5TWlWVFQ1aFJoOENwYU9ha29TcDBcbi9aODFSdHBPN3dLQmdRQ2NETmlQTHdPUWZqc2xXTjBZN3ozeWpNWXA4VnlVWmVHSmtNeCtPZ2dSYmVDSHp6dFlcblJGdk9zTmE4bHc5ajNES0dERlkwa3JTd1RjeitwTlF4MWk2ODJlQjFNZEdGNlFabDlicjlVeTduOFArdzFXLzJcbkZBS2xSakVFeVF0QTBBRXZIZlQvc0JCdStLRnZRenhkcndCQlZBMGZVUVVGdmZXNS9FeGVLUEU2TlFLQmdRQ1NcbmZIU00yd2FWbVhMUGY5UGJxVjM5ZUltR2wrK2lJNm9XVVFoUFJUdTdoQWVrKzEydFFEbWhRZDFweHU2RjVzcTNcbktydml5RTEydjdJK1AyYk9lK2F3NmdOWmNwVVhwUTl5bWgvMFlCbG1xayt5WkdqTDlOU3ZBc05xdmh4L29PNGhcblhXWUtwTzZkK1M3QzhmVzVjN0x1M1hvN201RFJmZ3hqcWE3NFFKRXVEUUtCZ0NQdWZFSjFnSlNkSGRFaDF5RzJcbi9KSVZYYlBVdk5sNUQySEFxdE5neE9paHlCMi9JZ2s0Vzk4K1dCSUFyblhMNGJCcFlmTXZUVDVURXllNmxkQS9cbjdaeUtBNi9pcjl3djd1VHhhQmVEUHlFNU92RmVEcVI0QkU3RVFlM2ZNOVg4WXZHODQvemJKRG1UVmFSY1BDK1pcbmdMTjB5U2VBU1ZqWTh5VmNrMmlCQmpsS1xuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogIm5pZnR5LW1lbW9yeS0yODQ4MTZAYXBwc3BvdC5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwMDIyMTQxMjAwMjQzMzA5NjE1NSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvbmlmdHktbWVtb3J5LTI4NDgxNiU0MGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
        project_id: nifty-memory-284816

    - name: Publish app to Google App Engine
      run: |
        # This client-secret.json is converted by GCP_SA_KEY.
        gcloud auth activate-service-account github@nifty-memory-284816.iam.gserviceaccount.com --key-file=jintou1-32abd731baf2.json
        gcloud config set project nifty-memory-284816
        gcloud -q app deploy app.yaml
        
        # Suppose you need a cron task.
        # gcloud -q app deploy cron.yaml